### ISSUE TITLE
d2asset.go:88: error loading file

### ISSUE THREAD

**Issue by SpaceAgeHero** [OpenDiablo2/OpenDiablo2#329]
**Describe the bug**
After changing Language from ENG to DEU or FRA as described on https://opendiablo2.com/#config in config.json, OpenDiablo2 fails to launch.
Error message:
d2asset.go:88: error loading file /data/local/lng/{LANG}/string.tbl (file not found)
main.go:76: file not found

**To Reproduce**
As described above.

**Expected behavior**
Launch with desired language.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: I use Arch btw
 - Version: opendiablo2-git r486.515b667-1 https://aur.archlinux.org/packages/opendiablo2-git

**Additional context**
Diablo 2 was installed into Wine from CD media including LOD expansion. After that LODPatch_114d.exe was applied.

**Comment by essial** [comment]
Can you jump on discord and supply me with your mpq files so I can test/troubleshoot? Also can you verify all MPQs in your install are being loaded?

**Comment by SpaceAgeHero** [comment]
Thanks for the fast reply. Just messaged you on discord.

**Comment by poplarch** [comment]
same here
OS: Deepin Linux 15.11
Version: git latest
after changing Language to CHI, the same situation came out.

**Comment by liberodark** [comment]
Same for me : 

Commit : 16dc775be17342bdfda285849dae57abf28cbb6a
Have speak about this problem on discord on long time ago and found the commit working too.

```
./OpenDiablo2
main.go:77: OpenDiablo2 - Open source Diablo 2 engine
d2config.go:32: loading configuration file from config.json...
d2config.go:32: loading configuration file from /home/pc/.config/OpenDiablo2/config.json...
d2render.go:19: Initialized the Ebiten renderer...
level_types.go:51: Loaded 38 LevelType records
level_presets.go:88: Loaded 1091 level presets
level_warp.go:47: Loaded 83 level warps
object_types.go:29: Loaded 573 object types
objects.go:352: Loaded 571 objects
weapons.go:13: Loaded 307 weapons
armor.go:13: Loaded 203 armors
misc.go:13: Loaded 152 misc items
unique_items.go:134: Loaded 352 unique items
missiles.go:305: Loaded 684 missiles
sounds.go:102: Loaded 4699 sound definitions
animation_data.go:46: Loaded 3529 animation data records
item_affix.go:64: Loaded 670 MagicPrefix records
item_affix.go:64: Loaded 748 MagicSuffix records
itemstatcost.go:319: Loaded 359 ItemStatCost records
d2asset.go:88: error loading file /data/local/lng/{LANG}/string.tbl (file not found)
main.go:80: file not found
```

**Comment by gravestench** [comment]
tested all language settings with pull request #383 , doesn't crash anymore, but I don't think it's the right solution. I dont seem to have fonts/translation string tables for some of the languages in my mpq's, not sure what the differences are with all mpq's are.

Here's a post from 2010 where missing translations are discussed: https://www.diabloii.net/forums/threads/other-diablo-2-localizations.758236/

If the mpq's are actually missing translation data and fonts, I think the best solution would be for us to author our own mpq with the missing string table and font files and to keep it in the OpenDiablo2 git repo.

Thoughts?

**Comment by essial** [comment]
@SpaceAgeHero @poplarch @liberodark can you guys confirm this has been fixed with the latest changes to master?

**Comment by liberodark** [comment]
Not fixed.
Tested on commit : 5e1725dd7d5c450d101f47f71957a3f6fb49ae1a

```
main.go:82: OpenDiablo2 - Open source Diablo 2 engine
d2config.go:31: loading configuration file from config.json...
d2config.go:31: loading configuration file from /home/pc/.config/OpenDiablo2/config.json...
d2render.go:19: Initialized the Ebiten renderer...
level_types.go:51: Loaded 38 LevelType records
level_presets.go:88: Loaded 1091 level presets
level_warp.go:47: Loaded 83 level warps
object_types.go:29: Loaded 573 object types
objects.go:352: Loaded 571 objects
weapons.go:13: Loaded 307 weapons
armor.go:13: Loaded 203 armors
misc.go:13: Loaded 152 misc items
unique_items.go:132: Loaded 352 unique items
missiles.go:304: Loaded 684 missiles
sounds.go:102: Loaded 4699 sound definitions
animation_data.go:46: Loaded 3529 animation data records
monstats.go:1057: Loaded 734 MonStats records
item_affix.go:61: Loaded 670 MagicPrefix records
item_affix.go:61: Loaded 748 MagicSuffix records
itemstatcost.go:320: Loaded 359 ItemStatCost records
charstats.go:189: Loaded 8 CharStats records
monstats.go:1057: Loaded 734 MonStats records
hireling.go:164: Loaded 120 Hireling records
experience.go:111: Loaded 100 ExperienceBreakpoint records
gems.go:108: Loaded 68 Gems records
difficultylevels.go:121: Loaded 3 DifficultyLevel records
automap.go:98: Loaded 3287 AutoMapRecord records
levels.go:535: Loaded 138 LevelDetails records
level_maze.go:55: Loaded 81 LevelMazeDetails records
level_sub.go:100: Loaded 13 LevelSubstitution records
d2asset.go:89: error loading file data\local\lng\fra\string.tbl (file not found)
main.go:85: file not found

```

**Comment by essial** [comment]
@gravestench

**Comment by gravestench** [comment]
I can verify that the files we're looking for do exist int the mpq:
```
-rw-rw-r-- 1 dk dk 419255 Dec 31  1969  d2data/data/local/LNG/FRA/string.tbl
-rw-rw-r-- 1 dk dk 196761 Dec 31  1969  d2exp/data/local/lng/fra/expansionstring.tbl
-rw-rw-r-- 1 dk dk  37347 Dec 31  1969  d2exp/data/local/lng/fra/patchstring.tbl
```

I followed this in GoLand debugger. the file that ends up causing the error is: `d2data/data/local/LNG/FRA/string.tbl`, the other two files load up properly.

Problems start happening in `d2common/d2fileformats/d2mpq/mpq.go`.
`MPQ.HashEntryMap.Find` does find the file, but the check on line 247 of mpq.go is where the file is considered as not found.

Here's what I'm seeing in debugger:
![image](https://user-images.githubusercontent.com/936440/85324946-9f056a80-b47f-11ea-8aa2-f87a2f356ea0.png)

**Comment by gravestench** [comment]
This looks like it's a bug with  `archiveManager` in `d2asset/d2core/archive_manager.go`.

when `loadArchiveFor(filepath)` is called, it eventually ends up trying to us `d2exp.mpq` instead of `d2data.mpq` for loading the string table file `data/local/LNG/FRA/string.tbl`.

It should be using `d2data.mpq`, not `d2exp.mpq`!

**Comment by wasted-bit** [comment]
same for me @ arch linux
tested on commit  226181f
d2base+lod 1.14b german installers

i remember earlier versions of the game required additional patches
for the german version. i have them on cdrom and would non-publicly 
uploud the patches, if they can point in the right direction.

**console output:**
```
main.go:74: OpenDiablo2 - Open source Diablo 2 engine
d2config.go:31: loading configuration file from config.json...
d2config.go:31: loading configuration file from /home/wasted/.config/OpenDiablo2/config.json...
d2render.go:19: Initialized the Ebiten renderer...
level_types.go:51: Loaded 38 LevelType records
level_presets.go:88: Loaded 1091 level presets
level_warp.go:47: Loaded 83 level warps
object_types.go:29: Loaded 573 object types
objects.go:352: Loaded 571 objects
weapons.go:13: Loaded 307 weapons
armor.go:13: Loaded 203 armors
misc.go:13: Loaded 152 misc items
unique_items.go:132: Loaded 352 unique items
missiles.go:304: Loaded 684 missiles
sounds.go:102: Loaded 4699 sound definitions
animation_data.go:46: Loaded 3529 animation data records
monstats.go:1057: Loaded 734 MonStats records
item_affix.go:61: Loaded 670 MagicPrefix records
item_affix.go:61: Loaded 748 MagicSuffix records
itemstatcost.go:320: Loaded 359 ItemStatCost records
charstats.go:189: Loaded 8 CharStats records
monstats.go:1057: Loaded 734 MonStats records
hireling.go:164: Loaded 120 Hireling records
experience.go:111: Loaded 100 ExperienceBreakpoint records
gems.go:108: Loaded 68 Gems records
difficultylevels.go:121: Loaded 3 DifficultyLevel records
automap.go:100: Loaded 3287 AutoMapRecord records
levels.go:545: Loaded 138 LevelDetails records
level_maze.go:55: Loaded 81 LevelMazeDetails records
level_sub.go:100: Loaded 13 LevelSubstitution records
cubemain.go:219: Loaded 151 CubeMainRecord records
super_uniques.go:149: Loaded 67 SuperUnique records
d2asset.go:88: error loading file /data/local/lng/{LANG}/string.tbl (file not found)
main.go:80: file not found
```

**config file**
```
{
    "MpqLoadOrder": [
        "Patch_D2.mpq",
        "d2exp.mpq",
        "d2xmusic.mpq",
        "d2xtalk.mpq",
        "d2xvideo.mpq",
        "d2data.mpq",
        "d2char.mpq",
        "d2music.mpq",
        "d2sfx.mpq",
        "d2video.mpq",
        "d2speech.mpq"
    ],
    "Language": "DEU",
    "MpqPath": "/home/wasted/Games/Opendiablo2/Diablo2/Diablo II/",
    "TicksPerSecond": -1,
    "FpsCap": 0,
    "SfxVolume": 1,
    "BgmVolume": 0.3,
    "FullScreen": true,
    "RunInBackground": true,
    "VsyncEnabled": true
}
```

**Comment by gravestench** [comment]
I'm getting a copy of every available version from blizzard and will look into this further once I have mpq's for each locale

**Comment by gravestench** [comment]
The MPQ's are hard-coded to have a specific locale, and there is a file within the mpq which signifies the locale of the mpq. We shouldn't even have the language as an option in our config file.
