### ISSUE TITLE
Add "help" panel

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#686]
Here it is from original diablo 2:
![image](https://user-images.githubusercontent.com/936440/89367092-0fadc280-d68d-11ea-9639-931e93f0e577.png)

The keys displayed should reflect the current user keybindings

**Comment by brendanporter** [comment]
Largely addressed with https://github.com/OpenDiablo2/OpenDiablo2/pull/724

Still more work to be done. Close button doesn't have close behavior, and is missing icon.

**Comment by brendanporter** [comment]
Added close button in PR #731 
Font is still ugly on the close `0`

**Comment by brendanporter** [comment]
https://github.com/OpenDiablo2/OpenDiablo2/pull/739

Fixed close button appearance. That should be it for the basic overlay at this point.

**Comment by leahiel** [comment]
#758 solved most of the remaining issues.  Only two (known) issues remain:

Hotkeys should be reliant on the hotkeys used in game.  However the "Configure Controls" panel #753 isn't done, so this cannot be done. 
You can still click in the background while the help menu is open.

**Comment by joshjordan** [comment]
The latter issue, "You can still click in the background while the help menu is open", up for PR

**Comment by gucio321** [comment]
It was solved in #972
